[project]
name = "meal-prep-chatbot"
version = "0.1.0"
description = "A Streamlit chatbot for meal planning and cooking assistance"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.49.0",
    "mcp>=1.5.0",
    "mcp-agent>=0.0.10",
    "streamlit>=1.43.2",
]
